#!/bin/bash

# Usage: ./generateOptions.sh [<wolfssl-prefix-or-source-root>]
#
# Points the #cgo CFLAGS/LDFLAGS of every cgo-using package at a wolfSSL
# install. If the argument is an installed wolfSSL prefix (containing
# include/wolfssl/options.h), the paths point at that prefix. If it is a wolfSSL
# source root (containing wolfssl/options.h), or no argument is given, they
# point at /usr/local.

OPTIONS_H="../wolfssl/wolfssl/options.h"
DEFAULT_PREFIX="/usr/local"
PREFIX=""
DATE="$(date -u +%Y%m%d%H%M%S)"

CGO_FILES="aes.go wolftls/conn.go wolfx509/certgen_wolfcrypt.go \
           examples/client/client-psk.go examples/server/server-psk.go"

SUCCESS=0
on_exit() {
    for f in $CGO_FILES; do
        if [ "$SUCCESS" -eq 1 ]; then
            rm -f "$f.bak"
        elif [ -f "$f.bak" ]; then
            mv "$f.bak" "$f"
        fi
    done
    if [ "$SUCCESS" -eq 0 ]; then
        rm -f options.go
    fi
}

for f in $CGO_FILES; do
    if [ ! -f "$f" ]; then
        echo "Expected cgo-bearing file not found: $f"
        exit 99
    fi
done

if [ -n "$1" ]; then
    if [ ! -d "$1" ]; then
        echo "Path to wolfSSL is not a directory"
        exit 99
    fi

    # Ensure the path is in absolute format
    WOLFSSL_PATH=$(CDPATH= cd -- "$1" > /dev/null && pwd)
    if [ -z "$WOLFSSL_PATH" ]; then
        echo "Couldn't resolve $1 to an absolute path"
        exit 99
    fi

    echo "Path to wolfSSL was supplied."

    if [ -f "$WOLFSSL_PATH/include/wolfssl/options.h" ]; then
        OPTIONS_H="$WOLFSSL_PATH/include/wolfssl/options.h"
        PREFIX="$WOLFSSL_PATH"
        echo "wolfSSL install given, linking/building with $PREFIX"
    elif [ -f "$WOLFSSL_PATH/wolfssl/options.h" ]; then
        OPTIONS_H="$WOLFSSL_PATH/wolfssl/options.h"
    else
        echo "Couldn't find options.h, please supply the correct path to wolfSSL."
        exit 99
    fi
else
    echo "No path given, defaulting to ../wolfssl path."
    if [ ! -d ../wolfssl ];then
        echo "Couldn't find wolfSSL in default path, please supply the correct path to wolfSSL."
        exit 99
    fi
fi

if [ -z "$PREFIX" ]; then
    PREFIX="$DEFAULT_PREFIX"
    echo "wolfSSL install dir not given, linking/building with default prefix ($DEFAULT_PREFIX)."
fi

# When on Windows convert the path format
if command -v cygpath >/dev/null 2>&1; then
    PREFIX=$(cygpath -m "$PREFIX")
fi

case "$PREFIX" in
    *[!/_.:+[:alnum:]-]*)
        echo "Prefix contains characters a #cgo directive cannot express: $PREFIX"
        echo "Use a path made up of letters, digits and / _ . : + - only."
        exit 99
        ;;
esac

trap on_exit EXIT
trap 'exit 99' INT TERM

# The 'GOWOLFSSL_STAMP' lines below are not decorative. These help invalidate
# the cache generated by go (i.e., when wolfssl is rebuilt with the
# same configure).

rm -f options.go
echo "package wolfSSL"                                                      >> options.go
echo ""                                                                     >> options.go
echo "// #cgo CFLAGS: -g -Wall -I$PREFIX/include -DGOWOLFSSL_STAMP=$DATE"   >> options.go
echo "// #cgo LDFLAGS: -L$PREFIX/lib -lwolfssl -lm"                         >> options.go
sed 's/^/\/\/ /' "$OPTIONS_H"                                               >> options.go
if [ $? -ne 0 ]; then
    echo "Failed to generate options.go from $OPTIONS_H."
    exit 99
fi
echo "options.go generated from $OPTIONS_H."

# #cgo directives are package-scoped, so each cgo-using package carries one
# declaration. Replace the whole directive line to prevent drift.
sed -i.bak \
    -e "s|^// #cgo CFLAGS:.*|// #cgo CFLAGS: -g -Wall -I$PREFIX/include -DGOWOLFSSL_STAMP=$DATE|" \
    -e "s|^// #cgo LDFLAGS:.*|// #cgo LDFLAGS: -L$PREFIX/lib -lwolfssl -lm|" \
    $CGO_FILES
if [ $? -ne 0 ]; then
    echo "Failed to update cgo directives."
    exit 99
fi

for f in $CGO_FILES; do
    grep -q -- "-DGOWOLFSSL_STAMP=$DATE" "$f" || \
        { echo "$f stamp not updated"; exit 99; }
done

SUCCESS=1

echo "cgo paths pointed at $PREFIX."
echo "Success!"

exit 0
